name: CI/CD Pipeline - Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - master # Trigger on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install DVC
        run: |
          pip install dvc[all]

      - name: Set up AWS credentials for DVC
        env:
          S3_URI: ${{ secrets.S3_URI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dvc init
          dvc remote add -d origin $S3_URI
          dvc remote modify origin access_key_id $AWS_ACCESS_KEY_ID
          dvc remote modify origin secret_access_key $AWS_SECRET_ACCESS_KEY
          dvc remote modify origin region $AWS_REGION

      - name: Pull DVC datasets
        run: |
          dvc pull

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t hybrid-recommender-system:latest .

      - name: Run tests on Docker image
        run: |
          docker run --rm hybrid-recommender-system:latest pytest --maxfail=1 --disable-warnings -q

      - name: Log in to Docker Hub with Access Token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub Access Token

      - name: Push Docker image to Docker Hub
        run: |
          docker tag hybrid-recommender-system:latest ${{ secrets.DOCKER_USERNAME }}/hybrid-recommender-system:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hybrid-recommender-system:latest

      - name: Clean up Docker images
        run: |
          docker rmi hybrid-recommender-system:latest
